name: Build Image For Branch

on:
 
  push:
    branches: 
      - "**"

jobs:
  build_ts:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - 
      name: Setup Github Checkout Actions
      uses: actions/checkout@v3
    - 
      name: Setup Node Actions - Install dependencies & build Typescript code
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    -
      name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - 
      name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ steps.extract_branch.outputs.branch }}

      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG