name: Docker


on: 
  push: 
    branches: [ main ]

jobs: 
  build_ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 14.12.8
      - run: npm ci
      - run: npm run build
