name: Docker


on: [push]

job: 
  build: 
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: docker build
      - run: |
          docker build . -t hawi1995/hello-gameel:1.0.0
          
