name: Docker


on: 
  push: 
    branches: [ main ]

jobs: 
  build_ts:
    runs-on: ubuntu-latest
    steps:
    -
      name: Setup Checkout Actions 
      uses: actions/checkout@v3
    -
      name: Setup Node Actions
      uses: actions/setup-node@v3
      with: 
          node-version: 14
          cache: 'npm'
    - run: npm ci  
    - run: npm run build
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with: 
        username: hawi1995
        password: yxa6qax4fba.tkc4QDF
    -
      name: Build and push Docker
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: hawi1995/hello-gameel:latest